使用pickle序列化numpy array

In [25]:

import pickle
import numpy as np


In [26]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
f = open('x.pkl','wb')

In [28]:
pickle.dump(x,f)

In [29]:
!ls

'ls' �����ڲ����ⲿ���Ҳ���ǿ����еij���
���������ļ���


In [30]:
f = open('x.pkl','rb')

In [31]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

使用numpy来进行序列化

In [32]:
np.save('one.array',x)

In [33]:
!ls

'ls' �����ڲ����ⲿ���Ҳ���ǿ����еij���
���������ļ���


In [37]:
y = np.arange(20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
np.savez('two_array.npz',a=x,b=y)

In [39]:
c = np.load('two_array.npz')

In [40]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])