#快速创建数组

In [1]:
import numpy as np
np.random.randn(10)

array([ 0.27101475,  0.5229944 , -0.46785674, -0.08567691,  0.18008507,
       -0.217563  , -2.43025937,  0.2391671 , -3.36410733, -1.24788954])

In [2]:
np.random.randint(10)

7

In [3]:
# 创造n维数组
np.random.randint(10,size=(2,3))

array([[4, 7, 3],
       [5, 2, 2]])

In [4]:
np.random.randint(10,size=20).reshape(4,5) #reshape可以重铸

array([[7, 5, 9, 6, 9],
       [9, 7, 5, 3, 1],
       [5, 8, 6, 9, 8],
       [7, 4, 1, 8, 1]])

#数组的运算

In [5]:
a = np.random.randint(10,size=20).reshape(4,5)
b = np.random.randint(10,size=20).reshape(4,5)
a

array([[2, 3, 9, 8, 3],
       [5, 3, 6, 3, 2],
       [4, 6, 7, 1, 0],
       [1, 0, 3, 4, 0]])

In [6]:
b

array([[9, 8, 8, 9, 0],
       [5, 2, 2, 7, 2],
       [5, 0, 1, 4, 0],
       [0, 3, 6, 3, 7]])

In [7]:
a+b

array([[11, 11, 17, 17,  3],
       [10,  5,  8, 10,  4],
       [ 9,  6,  8,  5,  0],
       [ 1,  3,  9,  7,  7]])

In [8]:
a-b

array([[-7, -5,  1, -1,  3],
       [ 0,  1,  4, -4,  0],
       [-1,  6,  6, -3,  0],
       [ 1, -3, -3,  1, -7]])

In [9]:
a*b

array([[18, 24, 72, 72,  0],
       [25,  6, 12, 21,  4],
       [20,  0,  7,  4,  0],
       [ 0,  0, 18, 12,  0]])

In [10]:
#a/b 会报错

In [11]:
# 创建矩阵的函数
np.mat([[1,2,3],[3,4,5]])

matrix([[1, 2, 3],
        [3, 4, 5]])

In [12]:
a #也可以直接转换

array([[2, 3, 9, 8, 3],
       [5, 3, 6, 3, 2],
       [4, 6, 7, 1, 0],
       [1, 0, 3, 4, 0]])

In [13]:
np.mat(a)

matrix([[2, 3, 9, 8, 3],
        [5, 3, 6, 3, 2],
        [4, 6, 7, 1, 0],
        [1, 0, 3, 4, 0]])

In [14]:
# 矩阵的运算

In [15]:
A = np.mat(a)

In [16]:
B = np.mat(b)

In [17]:
A + B

matrix([[11, 11, 17, 17,  3],
        [10,  5,  8, 10,  4],
        [ 9,  6,  8,  5,  0],
        [ 1,  3,  9,  7,  7]])

In [18]:
A - B

matrix([[-7, -5,  1, -1,  3],
        [ 0,  1,  4, -4,  0],
        [-1,  6,  6, -3,  0],
        [ 1, -3, -3,  1, -7]])

In [19]:
A * B

ValueError: shapes (4,5) and (4,5) not aligned: 5 (dim 1) != 4 (dim 0)

In [ ]:
a = np.mat(np.random.randint(10,size=20).reshape(4,5))
b = np.mat(np.random.randint(10,size=20).reshape(5,4))
a

matrix([[5, 4, 1, 7, 3],
        [0, 6, 8, 2, 2],
        [3, 1, 9, 4, 7],
        [2, 6, 1, 6, 2]])

In [ ]:
b

matrix([[0, 1, 4, 3],
        [1, 8, 5, 4],
        [3, 5, 9, 0],
        [4, 9, 8, 6],
        [4, 7, 0, 6]])

#使用array的频率要多一些
Array常用函数

In [ ]:
a = np.random.randint(10,size=20).reshape(4,5)

In [ ]:
np.unique(a) #10以内的 输出函数

array([0, 1, 2, 3, 5, 6, 7, 8, 9])

In [ ]:
a

array([[5, 6, 5, 9, 1],
       [9, 2, 6, 2, 8],
       [2, 6, 7, 3, 6],
       [0, 2, 0, 9, 8]])

In [ ]:
sum(a)

array([16, 16, 18, 23, 23])

In [ ]:
sum(a[0])

26

In [ ]:
sum(a[:,0])

16

In [ ]:
a.max()

9

In [ ]:
max(a[0])

9