In [1]:
from pandas import Series

创建 Create

In [2]:
a = [1,2,3,4]
s = Series(a)
s

0    1
1    2
2    3
3    4
dtype: int64

In [7]:
s.index
s.values
#dtype是values的种类

array([1, 2, 3, 4], dtype=int64)

In [8]:
s1 = Series(a,index=['A','B','C','D'])
s1.index

Index(['A', 'B', 'C', 'D'], dtype='object')

通过Numpy创建series

In [11]:
import numpy as np
s2 = Series(np.arange(5))
s2.values

array([0, 1, 2, 3, 4])

In [13]:
d = {'A':1,'B':2,'C':3,'D':4}
s3 = Series(d)
s3

A    1
B    2
C    3
D    4
dtype: int64

In [14]:
s3.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [15]:
s3.values

array([1, 2, 3, 4], dtype=int64)

In [16]:
#把serires转换成字典
s3.to_dict()

{'A': 1, 'B': 2, 'C': 3, 'D': 4}

In [17]:
s3

A    1
B    2
C    3
D    4
dtype: int64

In [18]:
s3['A']

1

In [19]:
s3[s3>2]

C    3
D    4
dtype: int64

In [20]:
type(s3[s3>2])

pandas.core.series.Series

In [25]:
#直接按到tab 可以查看有什么用法
s3.pop('A')
s3.pop('B') 

2

In [29]:
s4 = Series(s3,index=['B','C','D'])
s4

B    NaN
C    3.0
D    4.0
dtype: float64

In [31]:
s4.isnull()
#B就可以等于true

B     True
C    False
D    False
dtype: bool

In [33]:
s4.notnull()
s4

B    NaN
C    3.0
D    4.0
dtype: float64

In [34]:
s5 = Series(s4,index=['C','D'])
s5

C    3.0
D    4.0
dtype: float64