使用pickle序列化numpy array

In [1]:

import pickle
import numpy as np


In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
f = open('x.pkl','wb')

In [4]:
pickle.dump(x,f)

In [5]:
!ls

'ls' �����ڲ����ⲿ���Ҳ���ǿ����еij���
���������ļ���


In [6]:
f = open('x.pkl','rb')

In [7]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

使用numpy来进行序列化

In [8]:
np.save('one.array',x)

In [9]:
!ls

'ls' �����ڲ����ⲿ���Ҳ���ǿ����еij���
���������ļ���


In [10]:
y = np.arange(20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
np.savez('two_array.npz',a=x,b=y)

In [12]:
c = np.load('two_array.npz')

In [13]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])