In [18]:
import numpy as np

In [19]:
list_1 = [1,2,3,4,5,6]
array_1 = np.array(list_1)
array_1

array([1, 2, 3, 4, 5, 6])

In [20]:
list_2 = [2,3,4,52,5,6]
array_2 = np.array([list_1,list_2])
array_2

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  3,  4, 52,  5,  6]])

In [21]:
array_2.shape #返回数组的行列

(2, 6)

In [22]:
array_2.size #返回数组元素中的个数

12

In [23]:
array_2.dtype #返回数字的数据类型

dtype('int32')

In [24]:
array_3 = np.array([[1.0,3.0,4.5],[2.54,4.3,234.5]])
array_3.dtype

dtype('float64')

In [25]:
array_4 = np.arange(1,10) #有点像random
array_4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
#创造全0矩阵 一维的矩阵
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.eye(5) # 五维矩阵

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.eye(5).dtype

dtype('float64')

In [29]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a[0]

1

In [31]:
b = np.array([[1,2,3],[5,4,2]])
b

array([[1, 2, 3],
       [5, 4, 2]])

In [32]:
b[1,0] #通过查找第几行第几列来做

5

In [33]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
#进行二位数组的切片
c[:2,1:]

array([[2, 3],
       [5, 6]])