In [8]:
import numpy as np
#向量
a = np.array([1,2,3,4,5])
print(a)
b = np.array([0.11,0.33])
print(b)

[1 2 3 4 5]
[0.11 0.33]


In [9]:
#矩阵
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [10]:
#张量 和维度很像
d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [11]:
#求范数
#L1范数
e = np.array([1,1,-1,-1])
print('L1范数\n',np.linalg.norm(a))
#L2范数
print('L2范数\n',np.linalg.norm(a,1))

L1范数
 7.416198487095663
L2范数
 15.0
