In [17]:
#向量和标量
import numpy as np

a = np.array([1,2,3,4,5])
print(a)
b = np.array([0.21,0.33])
print(b)

[1 2 3 4 5]
[0.21 0.33]


In [18]:
#矩阵
c = np.array([[1,2,3],[4,5,6]])
print(c)

d = np.array([[0.21,0.14],[-0.3,0.81]])
print(d)

[[1 2 3]
 [4 5 6]]
[[ 0.21  0.14]
 [-0.3   0.81]]


In [19]:
#张量
e = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(e)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
